### ISSUE TITLE
Admin Event Detail Page Frontend

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-user#69]
## Current Event Detail Page:  
<img width="1512" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-user/assets/98133282/279475a8-c5ee-4433-9e90-c89cdbf0a9c2">  
<img width="1356" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-user/assets/98133282/245d2517-5275-4bf1-b7ad-2efe218e56ed">  

## Design:  
<img width="762" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-user/assets/98133282/c8ffc4de-3d42-4363-9bc4-97c50b229a28">  
<img width="937" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-user/assets/98133282/1bd34d94-49f8-4889-8d1c-418537da8157">  
<img width="677" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-user/assets/98133282/522f6f1a-198c-43c8-a7b6-1272b54bbd73">  
<img width="676" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-user/assets/98133282/75ce6258-e2c5-4297-8c16-d86a44e3b336">  

## Tasks
- [ ] Fill in the missing title and buttons
- [ ] Implement the `Edit` functionality
- [ ] If you have time, make the edit popup window look like the design.
