### ISSUE TITLE
Finish Volunteer Log Hour Flow

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-user#70]
## Tasks
- [x] Display all events a user has signed up for **and** the endDate has not passed today's date
<img width="807" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-user/assets/98133282/239ac5c5-e967-4153-97f6-c49f9f8d0053">

- [x] Prompt user for "date visited", "number of hours", and "books distributed"
<img width="921" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-user/assets/98133282/71cde6c9-7deb-4a09-bf71-b3f760ce93b3">

- [x] Implement the submit button and see if database gets updated. Don't follow the Figma design for the "comment" page and remove the "Program" page in current code.
