### ISSUE TITLE
Picture Upload

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-user#76]
## Tasks
This can be challenging because most likely you have not worked with AWS S3 before, but we'll get through it together. Book'em wants to see the volunteers' photos when they register. It is currently in the very last step of the user registration process, but I don't think the functionality works. 
- [ ] Set up AWS credentials in .env file. Ask me for the AWS account and the secrets. 
- [ ] Figure out the frontend logic for uploading. We can build the upload from scratch or rely on [antd](https://ant.design/components/upload).
- [ ] Upload the file to backend and store it locally (for testing only).
- [ ] Upload the file to S3 bucket.
<img width="1512" alt="image" src="https://github.com/ChangePlusPlusVandy/bookem-user/assets/98133282/77764da5-82d6-472f-8664-05f2c014574a">

## More resources
* AWS S3 [Doc](https://aws.amazon.com/s3/)
* AWS S3 SDK for Node.js [Doc](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/javascript_s3_code_examples.html)
* When you're handling file/binary data in the backend, you would need to use the [multer](https://www.npmjs.com/package/multer) middleware. However, Next.js has some weird restrictions when running a middleware. I managed to figure it out for my research project, but it's a closed-source project so I can't share you the code (publicly), so you can ask me for help on that.
