### ISSUE TITLE
New Backend API endpoints for new models

### ISSUE THREAD

**Issue by JiashuHarryHuang** [ChangePlusPlusVandy/bookem-user#77]
## Tasks
- [ ] `/api/event/<id>/apply/`
    - [ ] GET: Return a list of application questions that this event needs
    - [ ] POST: Submit the answers to the questions this event needs
- [ ] `/api/event/<id>/application`
    - [ ] GET: Get submitted application
- [ ] `/api/applications`
    - [ ] GET: Get all applications to all applied events
